/* Generated By:JavaCC: Do not edit this line. BasicParserConstants.java */
package fr.utbm.info.da53.lw2.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasicParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CR = 5;
  /** RegularExpression Id. */
  int EQ = 6;
  /** RegularExpression Id. */
  int LT = 7;
  /** RegularExpression Id. */
  int LE = 8;
  /** RegularExpression Id. */
  int GT = 9;
  /** RegularExpression Id. */
  int GE = 10;
  /** RegularExpression Id. */
  int NE = 11;
  /** RegularExpression Id. */
  int PLUS = 12;
  /** RegularExpression Id. */
  int MINUS = 13;
  /** RegularExpression Id. */
  int MULTIPLY = 14;
  /** RegularExpression Id. */
  int DIVIDE = 15;
  /** RegularExpression Id. */
  int OPAREN = 16;
  /** RegularExpression Id. */
  int CPAREN = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int PRINT = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int THEN = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int GOTO = 25;
  /** RegularExpression Id. */
  int GOSUB = 26;
  /** RegularExpression Id. */
  int LET = 27;
  /** RegularExpression Id. */
  int INPUT = 28;
  /** RegularExpression Id. */
  int RETURN = 29;
  /** RegularExpression Id. */
  int END = 30;
  /** RegularExpression Id. */
  int REM = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"REM (~[\\n])*\"",
    "\"\\n\"",
    "\"=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<NE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<STRING>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<PRINT>",
    "<IF>",
    "<THEN>",
    "<ELSE>",
    "<GOTO>",
    "<GOSUB>",
    "<LET>",
    "<INPUT>",
    "<RETURN>",
    "<END>",
    "<REM>",
  };

}
